### ISSUE TITLE
panic does not stacktrace anymore

### ISSUE THREAD

**Issue by SkinyMonkey** [stretchr/testify#735]
Until recently when my code panicked I had a nice stacktrace right away to help me fix my pb.
Now I only get a useless "suite.go:61: test panicked: ..."
and i have to manually add a recover handler to display it.

Did anything change recently?

**Comment by iliapolo** [comment]
@SkinyMonkey how exactly did you add a "recover handler" to display the stacktrace? im new to Go and haven't been able to get it right. 

Can you share the code? hopefully a maintainer will address this issue soon because this is very frustrating indeed.

**Comment by Azuka** [comment]
Likely needs #720 to be merged in.

**Comment by isaiah** [comment]
It's fixed in master https://github.com/stretchr/testify/blob/master/suite/suite.go#L62 
If you use go modules, you can pin to v1.2.0 for now.

**Comment by iliapolo** [comment]
@isaiah @Azuka Thanks :)

**Comment by SkinyMonkey** [comment]
I'm at 1.3.0 and still have the problem :/
Is it back?

**Comment by XSAM** [comment]
master: https://github.com/stretchr/testify/blob/master/suite/suite.go#L62
v1.3.0: https://github.com/stretchr/testify/blob/v1.3.0/suite/suite.go#L61

This code which prints stack still not been merged at `v1.3.0`

**Comment by rf** [comment]
Can we get this in a release? It's kind of a big deal that I don't get stack traces from panic in tests.

**Comment by yahudev** [comment]
Any update on this?

**Comment by machinae** [comment]
This is already in master. As a workaround, upgrade to the master version:

`go get github.com/stretchr/testify@master`

**Comment by paulcostinean** [comment]
This can be closed as it no longer happens on `v1.4.0`.

**Comment by marshallmcmullen** [comment]
Confirmed this is working properly with `v1.4.0` and higher. This can be closed...

**Comment by grosser** [comment]
@SkinyMonkey close please
